/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminLivraisonsRouteImport } from './routes/admin.livraisons'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminTransporteursIndexRouteImport } from './routes/admin.transporteurs.index'
import { Route as AdminMarchandsIndexRouteImport } from './routes/admin.marchands.index'
import { Route as AdminComptesIndexRouteImport } from './routes/admin.comptes.index'
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index'
import { Route as AdminTransporteursIdRouteImport } from './routes/admin.transporteurs.$id'
import { Route as AdminMarchandsIdRouteImport } from './routes/admin.marchands.$id'
import { Route as AdminCommandesIdRouteImport } from './routes/admin.commandes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivraisonsRoute = AdminLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransporteursIndexRoute = AdminTransporteursIndexRouteImport.update({
  id: '/transporteurs/',
  path: '/transporteurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarchandsIndexRoute = AdminMarchandsIndexRouteImport.update({
  id: '/marchands/',
  path: '/marchands/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComptesIndexRoute = AdminComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransporteursIdRoute = AdminTransporteursIdRouteImport.update({
  id: '/transporteurs/$id',
  path: '/transporteurs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarchandsIdRoute = AdminMarchandsIdRouteImport.update({
  id: '/marchands/$id',
  path: '/marchands/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesIdRoute = AdminCommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/marchands/': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs/': typeof AdminTransporteursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/commandes': typeof AdminCommandesIndexRoute
  '/admin/comptes': typeof AdminComptesIndexRoute
  '/admin/marchands': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs': typeof AdminTransporteursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/marchands/': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs/': typeof AdminTransporteursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/admin/'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/commandes/'
    | '/admin/comptes/'
    | '/admin/marchands/'
    | '/admin/transporteurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/admin'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/commandes'
    | '/admin/comptes'
    | '/admin/marchands'
    | '/admin/transporteurs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/admin/'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/commandes/'
    | '/admin/comptes/'
    | '/admin/marchands/'
    | '/admin/transporteurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livraisons': {
      id: '/admin/livraisons'
      path: '/livraisons'
      fullPath: '/admin/livraisons'
      preLoaderRoute: typeof AdminLivraisonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transporteurs/': {
      id: '/admin/transporteurs/'
      path: '/transporteurs'
      fullPath: '/admin/transporteurs/'
      preLoaderRoute: typeof AdminTransporteursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marchands/': {
      id: '/admin/marchands/'
      path: '/marchands'
      fullPath: '/admin/marchands/'
      preLoaderRoute: typeof AdminMarchandsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comptes/': {
      id: '/admin/comptes/'
      path: '/comptes'
      fullPath: '/admin/comptes/'
      preLoaderRoute: typeof AdminComptesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes/': {
      id: '/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AdminCommandesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transporteurs/$id': {
      id: '/admin/transporteurs/$id'
      path: '/transporteurs/$id'
      fullPath: '/admin/transporteurs/$id'
      preLoaderRoute: typeof AdminTransporteursIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marchands/$id': {
      id: '/admin/marchands/$id'
      path: '/marchands/$id'
      fullPath: '/admin/marchands/$id'
      preLoaderRoute: typeof AdminMarchandsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes/$id': {
      id: '/admin/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/admin/commandes/$id'
      preLoaderRoute: typeof AdminCommandesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminLivraisonsRoute: typeof AdminLivraisonsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommandesIdRoute: typeof AdminCommandesIdRoute
  AdminMarchandsIdRoute: typeof AdminMarchandsIdRoute
  AdminTransporteursIdRoute: typeof AdminTransporteursIdRoute
  AdminCommandesIndexRoute: typeof AdminCommandesIndexRoute
  AdminComptesIndexRoute: typeof AdminComptesIndexRoute
  AdminMarchandsIndexRoute: typeof AdminMarchandsIndexRoute
  AdminTransporteursIndexRoute: typeof AdminTransporteursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminLivraisonsRoute: AdminLivraisonsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommandesIdRoute: AdminCommandesIdRoute,
  AdminMarchandsIdRoute: AdminMarchandsIdRoute,
  AdminTransporteursIdRoute: AdminTransporteursIdRoute,
  AdminCommandesIndexRoute: AdminCommandesIndexRoute,
  AdminComptesIndexRoute: AdminComptesIndexRoute,
  AdminMarchandsIndexRoute: AdminMarchandsIndexRoute,
  AdminTransporteursIndexRoute: AdminTransporteursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
